# Site

title: "Introduction to basic NetLogo"
email: "cyberhelp@sesync.org"
description: "Meet the NetLogo environment for agent-based modeling."
styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.1
#styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
authors:
  - Nick Magliocca
lesson:

# Slides

slide_sorter:
  - title
  - turtles
  - environment
  - monitors
  - switches
  - behavior
  - plot
  - conclude

# Jekyll

markdown: kramdown
collections:
  - slides
